"""citations table

Revision ID: f9f27a4ec544
Revises: e517276bb1c2
Create Date: 2018-12-23 18:46:42.657612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f27a4ec544'
down_revision = 'e517276bb1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('SRR', sa.Integer(), nullable=True),
    sa.Column('TRT', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_index(op.f('ix_citation_timestamp'), 'citation', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citation_timestamp'), table_name='citation')
    op.drop_table('citation')
    # ### end Alembic commands ###
